#!/usr/bin/env bash
# Renders docker-compose.yml, Caddyfile, .env and the landing page for every
# team listed in teams.txt. Idempotent: re-run after editing teams.txt, then
# `docker compose up -d --remove-orphans`.
#
# Reads:  $N8N_DIR/.config, $N8N_DIR/teams.txt   (N8N_DIR defaults to /opt/n8n)
# Writes: docker-compose.yml, Caddyfile, .env (per-team encryption keys), www/index.html
set -euo pipefail

DIR="${N8N_DIR:-/opt/n8n}"
cd "$DIR"
# shellcheck disable=SC1091
source ./.config

mapfile -t TEAMS < <(sed -e 's/#.*//' -e 's/[[:space:]]//g' teams.txt | tr '[:upper:]' '[:lower:]' | grep -v '^$')
[[ ${#TEAMS[@]} -gt 0 ]] || { echo "teams.txt is empty" >&2; exit 1; }
for t in "${TEAMS[@]}"; do
  [[ $t =~ ^[a-z0-9]{2,20}$ ]] || { echo "invalid team name '$t' (lowercase letters/digits only)" >&2; exit 1; }
done

# ---- .env: one stable encryption key per team (never regenerate an existing one) ----
touch .env && chmod 600 .env
for t in "${TEAMS[@]}"; do
  key="N8N_KEY_${t^^}"
  grep -q "^${key}=" .env || echo "${key}=$(openssl rand -hex 24)" >> .env
done

# ---- docker-compose.yml ----
{
cat <<EOF
# Generated by gen-compose.sh — edit teams.txt and re-run instead of editing this file.
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./www:/srv/www:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]
EOF

for t in "${TEAMS[@]}"; do
cat <<EOF

  n8n-${t}:
    image: \${N8N_IMAGE}
    restart: unless-stopped
    environment:
      - N8N_HOST=${t}.${BASE_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://${t}.${BASE_DOMAIN}/
      - WEBHOOK_URL=https://${t}.${BASE_DOMAIN}/
      - N8N_PROXY_HOPS=1
      - N8N_ENCRYPTION_KEY=\${N8N_KEY_${t^^}}
      - GENERIC_TIMEZONE=\${TZ_NAME}
      - TZ=\${TZ_NAME}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_RUNNERS_ENABLED=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - n8n_${t}:/home/node/.n8n
    networks: [web]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5678/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
EOF
done

cat <<EOF

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
EOF
for t in "${TEAMS[@]}"; do echo "  n8n_${t}:"; done
} > docker-compose.yml

# compose reads image/timezone from .env too
grep -q '^N8N_IMAGE=' .env && sed -i "s#^N8N_IMAGE=.*#N8N_IMAGE=${N8N_IMAGE}#" .env || echo "N8N_IMAGE=${N8N_IMAGE}" >> .env
grep -q '^TZ_NAME=' .env  && sed -i "s#^TZ_NAME=.*#TZ_NAME=${TZ_NAME}#" .env     || echo "TZ_NAME=${TZ_NAME}" >> .env

# ---- Caddyfile ----
{
cat <<EOF
{
	email ${ACME_EMAIL}
}

# Landing page listing the team instances (no secrets on it)
${BASE_DOMAIN} {
	root * /srv/www
	file_server
}
EOF
for t in "${TEAMS[@]}"; do
cat <<EOF

${t}.${BASE_DOMAIN} {
	encode gzip
	reverse_proxy n8n-${t}:5678
}
EOF
done
} > Caddyfile

# ---- landing page ----
mkdir -p www
{
cat <<'EOF'
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>n8n Builders Challenge</title>
<style>
body{font-family:system-ui,sans-serif;background:#0f0b1e;color:#eee;margin:0;padding:40px 16px}
main{max-width:720px;margin:auto}h1{color:#ff6d5a}a{color:#fff}
ul{list-style:none;padding:0;display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:12px}
li{background:#1d1637;border-radius:10px;padding:16px 18px;font-size:1.1rem;text-transform:capitalize}
small{color:#aaa}
</style></head><body><main>
<h1>n8n Builders Challenge</h1>
<p>Open your team's instance. The first person to open it creates the owner account &mdash; choose a password the whole team will share.</p>
<ul>
EOF
for t in "${TEAMS[@]}"; do
  echo "<li><a href=\"https://${t}.${BASE_DOMAIN}\">${t}</a><br><small>${t}.${BASE_DOMAIN}</small></li>"
done
cat <<'EOF'
</ul></main></body></html>
EOF
} > www/index.html

echo "Rendered docker-compose.yml + Caddyfile for ${#TEAMS[@]} teams: ${TEAMS[*]}"
